### ISSUE TITLE
complex polygon convert to geojson

### ISSUE THREAD

**Issue by dyh333** [flq/GeoJsonAndSqlGeo#1]
hi, @flq  i have a complex polygon which is a lake and has some holes in it, the wkt string is shown below.
and i use GeoJsonAndSqlGeo and geojson.net to convert to geojson, the result is also shown below.
but i doubt the convertion is right because when i draw the geojson on map, it is not same as the polygon before converting.
so how can i handler the complex polygon, would you give me a hand, thank you very much.

**wkt**
"POLYGON ((120.68635741800006 31.326669202000062, 120.68599246800011 31.326905466000028, 120.6853246070001 31.328691780000042, 120.68453049700008 31.329130404000068, 120.68450263300008 31.330088139000054, 120.68450160200007 31.330349693000073, 120.6839405290001 31.330107749000035, 120.68352576900008 31.329127250000056, 120.68236407000006 31.328476528000067, 120.68173552200005 31.327747033000037, 120.68113462500003 31.325678813000025, 120.67957322700011 31.324821258000043, 120.67832191200011 31.324926083000037, 120.67886493700007 31.324253755000029, 120.67829347000009 31.324073800000065, 120.67867843100009 31.322942744000045, 120.67842313600011 31.322429974000045, 120.67773116000001 31.322246818000053, 120.67707972500011 31.322501637000073, 120.67677391000007 31.323994879000054, 120.67615710500002 31.324405222000053, 120.67672094700004 31.323921730000052, 120.6768834500001 31.322540528000047, 120.67760865700006 31.322180299000024, 120.67856459300003 31.322227923000071, 120.67890179200003 31.321753747000059, 120.67906369600007 31.320830296000054, 120.67797352400009 31.320655801000044, 120.6781134150001 31.320035634000078, 120.67762612400008 31.319955952000043, 120.67778953100003 31.319211755000026, 120.6783264820001 31.319054649000066, 120.67842057400003 31.31860024100007, 120.68123395400005 31.317787521000071, 120.68097193200003 31.31711974500007, 120.68015375100003 31.317062871000076, 120.68028449300004 31.316503024000042, 120.67986128000007 31.316146527000058, 120.68069104000006 31.313444111000024, 120.68080523200001 31.310860049000041, 120.68053162700005 31.309128024000074, 120.68005516500011 31.309312151000029, 120.67988279700012 31.308968427000025, 120.68016213300007 31.308627743000045, 120.67964238900004 31.307575155000052, 120.6797937230001 31.306618452000066, 120.67875267800002 31.305526794000059, 120.6788517760001 31.304845777000025, 120.67946985300011 31.304493567000065, 120.68159188900006 31.304677405000064, 120.68138106000004 31.303962240000033, 120.68011110400005 31.303699399000038, 120.68013976100008 31.303476717000024, 120.68089995700007 31.303442317000076, 120.68100445400012 31.302919691000056, 120.68114387300011 31.303151263000075, 120.68284963300005 31.303308344000072, 120.6842681390001 31.302512418000049, 120.68454138800007 31.301428216000033, 120.686284967 31.29897531000006, 120.68684004400006 31.29870315900007, 120.68687335400011 31.297952855000062, 120.68730397800005 31.297936721000042, 120.68732833900003 31.29859622400005, 120.68801155400001 31.299032530000034, 120.68819344200006 31.299661465000042, 120.68830477000006 31.299416165000025, 120.68870832700009 31.299846496000043, 120.68963225000005 31.299492293000071, 120.69038220100003 31.299716580000052, 120.69050646400001 31.300459427000078, 120.69011971600003 31.299809247000042, 120.68958393100002 31.299723448000066, 120.68904628400003 31.300314649000029, 120.68859600000008 31.300370826000062, 120.68904632500005 31.300351288000059, 120.68900082800008 31.30075774900007, 120.68956848300002 31.301157501000034, 120.6902917650001 31.301009774000079, 120.69050653200009 31.30051805100004, 120.69051354200008 31.300909250000075, 120.69092186600005 31.30089988800006, 120.6908461380001 31.30127086300007, 120.69202571200003 31.301721948000079, 120.6921904730001 31.302273101000026, 120.69173674800004 31.302767847000041, 120.6923708380001 31.303824236000025, 120.6944924610001 31.303650479000055, 120.69629036600008 31.303978099000062, 120.69798404400001 31.303886397000042, 120.69946633600011 31.302740758000027, 120.70289528100011 31.302293121000048, 120.70435853000004 31.30142902800003, 120.70625282500009 31.30143001700003, 120.70694129000003 31.300782794000042, 120.70736268600001 31.300848313000074, 120.70785029000001 31.301857256000062, 120.70932085400011 31.301978808000058, 120.70971926900006 31.301563612000052, 120.71013679500004 31.301562071000035, 120.71206169800007 31.303536459000043, 120.71268602900011 31.304011023000044, 120.71308248300011 31.303954816000044, 120.71281583500001 31.304832760000068, 120.71071984600007 31.305509045000065, 120.710698148 31.306940851000036, 120.7110680080001 31.307598313000028, 120.71187501500003 31.307779358000062, 120.71198287700008 31.30809455800005, 120.71257241800004 31.308092846000079, 120.71218729300006 31.308693015000074, 120.713138017 31.308952774000034, 120.71218412600001 31.308913328000074, 120.71252807400003 31.309019923000051, 120.71244931900003 31.30928153800005, 120.71152662700001 31.308827271000041, 120.71063113500009 31.308848460000036, 120.71052261900002 31.31016986700007, 120.70988233500009 31.311525624000069, 120.70986261400003 31.312484487000063, 120.71029997100004 31.31352068700005, 120.71159243000011 31.313787185000024, 120.71282383900007 31.313307307000059, 120.71331563300009 31.313681829000075, 120.71676945600007 31.313244647000033, 120.71805950300006 31.312703838000061, 120.71921518400006 31.31278773300005, 120.71916831600004 31.313068502000078, 120.71679921200007 31.313855661000048, 120.71507780400009 31.313951584000051, 120.71357666600011 31.314753568000071, 120.71157064200008 31.315114670000071, 120.71138561300006 31.315207866000037, 120.71197871400011 31.315838606000057, 120.71101167600011 31.316410035000047, 120.70828771600009 31.316101007000043, 120.70728096000005 31.317444705000071, 120.70639247000008 31.317863825000074, 120.70407752000006 31.320093752000048, 120.70361189800008 31.321573887000056, 120.70433203900006 31.321942989000036, 120.70415375200002 31.322189491000074, 120.70342048900011 31.321829419000039, 120.70208843800003 31.322551065000027, 120.69978377600012 31.32265747100007, 120.69843791400001 31.321783277000065, 120.69702983600007 31.321567517000062, 120.69639607200008 31.322016216000065, 120.69612132400005 31.322882856000035, 120.69625014300004 31.324074389000032, 120.69699270100011 31.324526939000066, 120.69687605000001 31.324720389000049, 120.69589502200006 31.32472745900003, 120.69474029100002 31.325551464000057, 120.69283631700011 31.325836086000038, 120.69164086800004 31.326691101000051, 120.68863215100009 31.326801286000034, 120.68702033200009 31.326473974000066, 120.68635741800006 31.326669202000062), (120.693816835 31.305258158000072, 120.69491047800011 31.306269604000079, 120.69654214200011 31.306984624000052, 120.69750430500005 31.30673235900008, 120.69899532200009 31.305165637000073, 120.69860932600011 31.304120896000029, 120.69663050200006 31.304032476000032, 120.69573029300011 31.304467879000072, 120.69438126800003 31.304000067000061, 120.69357564400002 31.304484979000051, 120.693816835 31.305258158000072), (120.69987567600003 31.312030635000042, 120.69967663700004 31.312480645000051, 120.70003826700008 31.312898012000062, 120.69995806100007 31.313873839000053, 120.70061791100011 31.314393524000025, 120.70139979500004 31.313788523000028, 120.70332533600003 31.313121006000074, 120.70408087200008 31.313494023000032, 120.70476220500007 31.312329348000048, 120.70382280600006 31.311930579000034, 120.70394860100009 31.310698226000056, 120.703468369 31.309955729000023, 120.70281537400001 31.309652510000035, 120.70247532200005 31.309684395000033, 120.70185128000003 31.310470202000033, 120.70247650800002 31.310619563000046, 120.7024192240001 31.311009693000074, 120.70333000500011 31.311632286000076, 120.70281719800005 31.312124307000033, 120.70298094000009 31.312843428000065, 120.70089796700006 31.31257309800003, 120.70070241600001 31.311607106000054, 120.69987567600003 31.312030635000042), (120.68671694700004 31.304968169000063, 120.68716044200005 31.304689342000074, 120.68684616900009 31.304270772000052, 120.68321804800007 31.304037476000076, 120.68209425700002 31.304181529000061, 120.6821854530001 31.304749663000052, 120.68262433200005 31.305060482000044, 120.68671694700004 31.304968169000063), (120.68678196300004 31.322297764000041, 120.68754622200004 31.322240772000043, 120.68782389300009 31.321572569000068, 120.68861996600003 31.321783862000075, 120.68899972700001 31.320819633000042, 120.6886764300001 31.320606824000038, 120.6882051880001 31.320797742000025, 120.6877031460001 31.320454862000076, 120.68715443300005 31.320657113000038, 120.68648955800006 31.321513902000049, 120.68678196300004 31.322297764000041), (120.69011655000008 31.303961991000051, 120.68936530600001 31.303785617000074, 120.68790732000002 31.304479602000072, 120.68795641100007 31.304936718000079, 120.68951921100006 31.305199237000068, 120.69027111900004 31.304795003000038, 120.69011655000008 31.303961991000051), (120.69043284600002 31.301531637000039, 120.69022858500011 31.302027296000063, 120.69080150700006 31.302429293000046, 120.6913429550001 31.302860628000076, 120.69199302300001 31.301839224000048, 120.6908646490001 31.301385277000065, 120.69043284600002 31.301531637000039), (120.69197082700009 31.304221981000069, 120.69129216900001 31.303228200000035, 120.69037106100006 31.303773504000048, 120.69055970400007 31.304548427000043, 120.69127637600002 31.304340383000067, 120.69171396700006 31.304648917000065, 120.69197082700009 31.304221981000069), (120.70307509000008 31.321820725000066, 120.70278208800005 31.321707134000064, 120.70169928000007 31.32220982900003, 120.6997856270001 31.322031207000066, 120.70041650300004 31.322439307000025, 120.70152635300008 31.322547641000028, 120.70307509000008 31.321820725000066), (120.69342307300008 31.304262450000067, 120.69246162800005 31.303990447000047, 120.6932112070001 31.304984163000029, 120.69342307300008 31.304262450000067), (120.71200880000004 31.313645049000058, 120.71201233300008 31.313649971000075, 120.71200985900009 31.313644679000049, 120.71200880000004 31.313645049000058), (120.70931661200007 31.301979161000077, 120.70932068000002 31.301979448000054, 120.70932084700007 31.301978837000036, 120.70931661200007 31.301979161000077))"

**geojson**
{"features":[{"geometry":{"coordinates":[[[120.68635741800006,31.326669202000062],[120.68599246800011,31.326905466000028],[120.6853246070001,31.328691780000042],[120.68453049700008,31.329130404000068],[120.68450263300008,31.330088139000054],[120.68450160200007,31.330349693000073],[120.6839405290001,31.330107749000035],[120.68352576900008,31.329127250000056],[120.68236407000006,31.328476528000067],[120.68173552200005,31.327747033000037],[120.68113462500003,31.325678813000025],[120.67957322700011,31.324821258000043],[120.67832191200012,31.324926083000037],[120.67886493700007,31.324253755000029],[120.67829347000009,31.324073800000065],[120.67867843100009,31.322942744000045],[120.67842313600011,31.322429974000045],[120.67773116000001,31.322246818000053],[120.67707972500011,31.322501637000073],[120.67677391000007,31.323994879000054],[120.67615710500002,31.324405222000053],[120.67672094700004,31.323921730000052],[120.67688345000011,31.322540528000047],[120.67760865700006,31.322180299000024],[120.67856459300003,31.322227923000071],[120.67890179200003,31.321753747000059],[120.67906369600007,31.320830296000054],[120.6779735240001,31.320655801000044],[120.6781134150001,31.320035634000078],[120.67762612400009,31.319955952000043],[120.67778953100003,31.319211755000026],[120.6783264820001,31.319054649000066],[120.67842057400003,31.31860024100007],[120.68123395400005,31.317787521000071],[120.68097193200003,31.31711974500007],[120.68015375100003,31.317062871000076],[120.68028449300005,31.316503024000042],[120.67986128000007,31.316146527000058],[120.68069104000006,31.313444111000024],[120.68080523200001,31.310860049000041],[120.68053162700005,31.309128024000074],[120.68005516500011,31.309312151000029],[120.67988279700012,31.308968427000025],[120.68016213300007,31.308627743000045],[120.67964238900004,31.307575155000052],[120.6797937230001,31.306618452000066],[120.67875267800002,31.305526794000059],[120.6788517760001,31.304845777000025],[120.67946985300011,31.304493567000065],[120.68159188900006,31.304677405000064],[120.68138106000004,31.303962240000033],[120.68011110400005,31.303699399000038],[120.68013976100008,31.303476717000024],[120.68089995700007,31.303442317000076],[120.68100445400012,31.302919691000056],[120.68114387300011,31.303151263000075],[120.68284963300005,31.303308344000072],[120.6842681390001,31.302512418000049],[120.68454138800007,31.301428216000033],[120.686284967,31.29897531000006],[120.68684004400006,31.29870315900007],[120.68687335400011,31.297952855000062],[120.68730397800005,31.297936721000042],[120.68732833900003,31.29859622400005],[120.68801155400001,31.299032530000034],[120.68819344200006,31.299661465000042],[120.68830477000006,31.299416165000025],[120.68870832700009,31.299846496000043],[120.68963225000005,31.299492293000071],[120.69038220100003,31.299716580000052],[120.69050646400001,31.300459427000078],[120.69011971600003,31.299809247000042],[120.68958393100002,31.299723448000066],[120.68904628400003,31.300314649000029],[120.68859600000008,31.300370826000062],[120.68904632500005,31.300351288000059],[120.68900082800008,31.30075774900007],[120.68956848300002,31.301157501000034],[120.6902917650001,31.301009774000079],[120.69050653200009,31.30051805100004],[120.69051354200008,31.300909250000075],[120.69092186600005,31.30089988800006],[120.6908461380001,31.30127086300007],[120.69202571200003,31.301721948000079],[120.6921904730001,31.302273101000026],[120.69173674800004,31.302767847000041],[120.6923708380001,31.303824236000025],[120.6944924610001,31.303650479000055],[120.69629036600009,31.303978099000062],[120.69798404400001,31.303886397000042],[120.69946633600011,31.302740758000027],[120.70289528100011,31.302293121000048],[120.70435853000004,31.30142902800003],[120.70625282500009,31.30143001700003],[120.70694129000003,31.300782794000042],[120.70736268600001,31.300848313000074],[120.70785029000001,31.301857256000062],[120.70932085400011,31.301978808000058],[120.70971926900006,31.301563612000052],[120.71013679500004,31.301562071000035],[120.71206169800007,31.303536459000043],[120.71268602900011,31.304011023000044],[120.71308248300011,31.303954816000044],[120.71281583500002,31.304832760000068],[120.71071984600008,31.305509045000065],[120.710698148,31.306940851000036],[120.7110680080001,31.307598313000028],[120.71187501500003,31.307779358000062],[120.71198287700008,31.30809455800005],[120.71257241800004,31.308092846000079],[120.71218729300006,31.308693015000074],[120.713138017,31.308952774000034],[120.71218412600001,31.308913328000074],[120.71252807400003,31.309019923000051],[120.71244931900003,31.30928153800005],[120.71152662700001,31.308827271000041],[120.71063113500009,31.308848460000036],[120.71052261900002,31.31016986700007],[120.70988233500009,31.311525624000069],[120.70986261400003,31.312484487000063],[120.71029997100004,31.31352068700005],[120.71159243000011,31.313787185000024],[120.71282383900007,31.313307307000059],[120.71331563300009,31.313681829000075],[120.71676945600007,31.313244647000033],[120.71805950300006,31.312703838000061],[120.71921518400006,31.31278773300005],[120.71916831600004,31.313068502000078],[120.71679921200007,31.313855661000048],[120.71507780400009,31.313951584000051],[120.71357666600011,31.314753568000071],[120.71157064200008,31.315114670000071],[120.71138561300006,31.315207866000037],[120.71197871400011,31.315838606000057],[120.71101167600011,31.316410035000047],[120.70828771600009,31.316101007000043],[120.70728096000005,31.317444705000071],[120.70639247000008,31.317863825000074],[120.70407752000006,31.320093752000048],[120.70361189800008,31.321573887000056],[120.70433203900006,31.321942989000036],[120.70415375200003,31.322189491000074],[120.70342048900011,31.321829419000039],[120.70208843800003,31.322551065000027],[120.69978377600012,31.32265747100007],[120.69843791400001,31.321783277000065],[120.69702983600007,31.321567517000062],[120.69639607200008,31.322016216000065],[120.69612132400005,31.322882856000035],[120.69625014300004,31.324074389000032],[120.69699270100011,31.324526939000066],[120.69687605000001,31.324720389000049],[120.69589502200006,31.32472745900003],[120.69474029100002,31.325551464000057],[120.69283631700012,31.325836086000038],[120.69164086800004,31.326691101000051],[120.68863215100009,31.326801286000034],[120.68702033200009,31.326473974000066],[120.68635741800006,31.326669202000062]],[[120.693816835,31.305258158000072],[120.69491047800011,31.306269604000079],[120.69654214200011,31.306984624000052],[120.69750430500005,31.30673235900008],[120.69899532200009,31.305165637000073],[120.69860932600011,31.304120896000029],[120.69663050200006,31.304032476000032],[120.69573029300011,31.304467879000072],[120.69438126800003,31.304000067000061],[120.69357564400002,31.304484979000051],[120.693816835,31.305258158000072]],[[120.69987567600003,31.312030635000042],[120.69967663700004,31.312480645000051],[120.70003826700008,31.312898012000062],[120.69995806100008,31.313873839000053],[120.70061791100011,31.314393524000025],[120.70139979500004,31.313788523000028],[120.70332533600003,31.313121006000074],[120.70408087200008,31.313494023000032],[120.70476220500007,31.312329348000048],[120.70382280600006,31.311930579000034],[120.70394860100009,31.310698226000056],[120.703468369,31.309955729000023],[120.70281537400001,31.309652510000035],[120.70247532200006,31.309684395000033],[120.70185128000003,31.310470202000033],[120.70247650800002,31.310619563000046],[120.7024192240001,31.311009693000074],[120.70333000500011,31.311632286000076],[120.70281719800005,31.312124307000033],[120.70298094000009,31.312843428000065],[120.70089796700006,31.31257309800003],[120.70070241600001,31.311607106000054],[120.69987567600003,31.312030635000042]],[[120.68671694700004,31.304968169000063],[120.68716044200005,31.304689342000074],[120.68684616900009,31.304270772000052],[120.68321804800007,31.304037476000076],[120.68209425700002,31.304181529000061],[120.6821854530001,31.304749663000052],[120.68262433200005,31.305060482000044],[120.68671694700004,31.304968169000063]],[[120.68678196300004,31.322297764000041],[120.68754622200004,31.322240772000043],[120.68782389300009,31.321572569000068],[120.68861996600003,31.321783862000075],[120.68899972700001,31.320819633000042],[120.6886764300001,31.320606824000038],[120.6882051880001,31.320797742000025],[120.6877031460001,31.320454862000076],[120.68715443300005,31.320657113000038],[120.68648955800006,31.321513902000049],[120.68678196300004,31.322297764000041]],[[120.69011655000008,31.303961991000051],[120.68936530600001,31.303785617000074],[120.68790732000002,31.304479602000072],[120.68795641100007,31.304936718000079],[120.68951921100006,31.305199237000068],[120.69027111900005,31.304795003000038],[120.69011655000008,31.303961991000051]],[[120.69043284600002,31.301531637000039],[120.69022858500011,31.302027296000063],[120.69080150700006,31.302429293000046],[120.6913429550001,31.302860628000076],[120.69199302300001,31.301839224000048],[120.69086464900011,31.301385277000065],[120.69043284600002,31.301531637000039]],[[120.69197082700009,31.304221981000069],[120.69129216900001,31.303228200000035],[120.69037106100006,31.303773504000048],[120.69055970400007,31.304548427000043],[120.69127637600002,31.304340383000067],[120.69171396700006,31.304648917000065],[120.69197082700009,31.304221981000069]],[[120.70307509000008,31.321820725000066],[120.70278208800005,31.321707134000064],[120.70169928000007,31.32220982900003],[120.6997856270001,31.322031207000066],[120.70041650300004,31.322439307000025],[120.70152635300008,31.322547641000028],[120.70307509000008,31.321820725000066]],[[120.69342307300008,31.304262450000067],[120.69246162800005,31.303990447000047],[120.6932112070001,31.304984163000029],[120.69342307300008,31.304262450000067]],[[120.71200880000004,31.313645049000058],[120.71201233300008,31.313649971000075],[120.71200985900009,31.313644679000049],[120.71200880000004,31.313645049000058]],[[120.70931661200007,31.301979161000077],[120.70932068000002,31.301979448000054],[120.70932084700007,31.301978837000036],[120.70931661200007,31.301979161000077]]],"type":"Polygon"},"properties":{"id":"461"},"type":"Feature"},{"geometry":{"coordinates":[[[120.69093517300007,31.297609022000074],[120.68759776400009,31.297655760000055],[120.68687335400011,31.297952855000062],[120.68638248100001,31.296902523000028],[120.68589201900011,31.29381104600003],[120.68505775200003,31.293264366000074],[120.68550675200004,31.292053752000072],[120.68439648900005,31.291210783000054],[120.68303624100008,31.291072619000033],[120.67878038600009,31.291427622000072],[120.67845303000001,31.292273410000064],[120.67912893500011,31.293351818000076],[120.68003661000012,31.293822383000077],[120.68168318200003,31.294039275000046],[120.68185945400012,31.294370592000064],[120.68143992800003,31.294942503000073],[120.68115830000011,31.294297852000057],[120.67857264100007,31.293710182000041],[120.67662597700007,31.292715570000041],[120.67411951100007,31.292490208000061],[120.67266262300007,31.292893716000037],[120.67201909800008,31.292656850000071],[120.67189673300004,31.292373396000073],[120.67227012000001,31.292017453000028],[120.67170873000009,31.290692020000051],[120.67201318900004,31.290568360000066],[120.67253870500008,31.290974418000076],[120.67294127500009,31.29185744800003],[120.67419896600006,31.291839647000074],[120.67576691800002,31.291078940000034],[120.67667061500004,31.290071239000042],[120.67715511800009,31.288826241000038],[120.6772596830001,31.28310633500007],[120.67787882100004,31.281333614000062],[120.67941501300004,31.279084442000055],[120.67871769100009,31.277499849000037],[120.67963543300004,31.277697018000026],[120.68036085400001,31.275961407000068],[120.68137411500004,31.27461790600006],[120.68172167000012,31.274344808000023],[120.68269047700005,31.27444270500007],[120.68346321000001,31.272839507000072],[120.6829806610001,31.272053527000025],[120.68438488900006,31.272605084000077],[120.68601584500004,31.272526320000054],[120.68879259800008,31.271932173000039],[120.69089278500007,31.270846431000052],[120.69240750800009,31.26860726600006],[120.69366362300002,31.268631553000034],[120.69474187100002,31.26475124600006],[120.69432844700009,31.263641685000039],[120.69523780700001,31.262390607000043],[120.69640522200007,31.261843920000047],[120.69651951700007,31.260843818000069],[120.69707909600004,31.260162371000035],[120.70318375400007,31.256540665000045],[120.70623775700005,31.253629079000063],[120.70822975200008,31.254542594000043],[120.70919044300001,31.254591259000051],[120.70984128400005,31.25551451900003],[120.71127724100006,31.255701929000054],[120.71233835200007,31.254319237000061],[120.712499148,31.252907573000073],[120.71250589300007,31.254000015000031],[120.71318587600001,31.255099103000077],[120.71426552300011,31.255751330000066],[120.71557547500004,31.255916273000025],[120.71528765400001,31.257067660000075],[120.71614837700008,31.258291106000058],[120.71556106000003,31.260614716000077],[120.71579226500012,31.261705798000037],[120.71343394500002,31.263049763000026],[120.71272468200004,31.264307887000029],[120.71266410200008,31.265499338000041],[120.7132597750001,31.266833539000061],[120.71552916400003,31.265950717000067],[120.71579604900012,31.265337137000074],[120.7169538280001,31.266384975000051],[120.71593851800003,31.266784004000044],[120.7144829990001,31.268703204000076],[120.71439859900011,31.270827016000055],[120.71565574300007,31.27287000900003],[120.7155783180001,31.27573645700005],[120.71609356500005,31.277164895000055],[120.71573706000004,31.277545197000052],[120.71644392900009,31.279258829000071],[120.71751542800007,31.279954545000066],[120.71990192500005,31.279241488000025],[120.72015434000002,31.279505592000078],[120.71685831400009,31.280504004000079],[120.71610206000003,31.281333988000029],[120.7159245040001,31.282024138000054],[120.71410810800012,31.282310111000072],[120.71410607600001,31.283684406000077],[120.71359960100006,31.285132658000066],[120.71238318500002,31.285174879000067],[120.70991423100008,31.283470476000048],[120.70906589800006,31.283239070000036],[120.70315567000012,31.284013067000046],[120.70164133700007,31.283599397000046],[120.70068929400009,31.28386757100003],[120.69992163900008,31.284461944000043],[120.69959755200011,31.285656149000033],[120.69741837600009,31.285663186000079],[120.69429640200008,31.28658419900006],[120.69379612200009,31.286487112000032],[120.69336353900008,31.28702863500007],[120.69188510400011,31.286817387000042],[120.6915127100001,31.286195563000035],[120.68875142600007,31.286927942000034],[120.68926533100012,31.287529698000071],[120.68853139200007,31.288007976000074],[120.68858928600002,31.288627131000055],[120.68919170600009,31.289526518000059],[120.69314733100009,31.289624643000025],[120.69298124300008,31.29017269700006],[120.69335912700001,31.291117128000053],[120.69393440700003,31.291336471000079],[120.69341125300002,31.291909639000039],[120.69377035400009,31.292500082000061],[120.69307949200004,31.294496161000041],[120.69354948600005,31.29560229100008],[120.69289707700011,31.295689098000025],[120.69240599900002,31.29677576000006],[120.69093517300007,31.297609022000074]],[[120.68635423600006,31.291489938000041],[120.68725380300009,31.292259118000061],[120.68685765400005,31.293228533000047],[120.68749321000007,31.294532409000055],[120.68717228000003,31.295189376000053],[120.68731923000007,31.296817326000053],[120.68795688100011,31.297094026000025],[120.6919504760001,31.296826881000072],[120.69235775400011,31.29593082100007],[120.6918494140001,31.294578385000079],[120.69243657400011,31.293704156000047],[120.69222131600009,31.29261471500007],[120.69265291300007,31.292328553000061],[120.6929366820001,31.291365518000077],[120.6924711580001,31.290695117000041],[120.68734815500011,31.290390488000071],[120.68650948800007,31.290599737000036],[120.68635423600006,31.291489938000041]]],"type":"Polygon"},"properties":{"id":"647"},"type":"Feature"}],"type":"FeatureCollection"}

**Comment by flq** [comment]
Hi, I am not sure I can help you. the data is too huge to be easily incorporated into a unit test. You could reduce the in and out to the actual coordonate pairs with regex and see if they match with any file diff tool. If we find a discrepancy we are a step closer to understanding.

Also, I think I never tested the lib with holes. Maybe you can reduce the issue to a smaller example which also fails? That would already be helpful.
